package org.jarbframework.violation.integration;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.util.HashMap;
import java.util.Map;

import javax.persistence.EntityManagerFactory;

import org.jarbframework.violation.DatabaseConstraintExceptionTranslator;
import org.jarbframework.violation.UniqueKeyViolationException;
import org.jarbframework.violation.domain.LicenseNumberAlreadyExistsException;
import org.jarbframework.violation.domain.LicenseNumberAlreadyExistsExceptionFactory;
import org.jarbframework.violation.factory.DatabaseConstraintViolationExceptionFactory;
import org.jarbframework.violation.factory.DefaultViolationExceptionFactory;
import org.jarbframework.violation.integration.JpaConstraintViolationExceptionTranslatorFactoryBean;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

/**
 * Factory should produce functional exception translators.
 * 
 * @author Jeroen van Schagen
 * @since 17-05-2011
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath:hsql-context.xml" })
public class ConstraintViolationExceptionTranslatorJpaFactoryBeanTest {
    private static final String UNIQUE_KEY_EXCEPTION_MESSAGE = "integrity constraint violation: unique constraint or index violation; uk_cars_license table: cars";

    @Autowired
    private EntityManagerFactory entityManagerFactory;

    private JpaConstraintViolationExceptionTranslatorFactoryBean factory;

    @Before
    public void setUp() throws Exception {
        factory = new JpaConstraintViolationExceptionTranslatorFactoryBean();
        factory.setEntityManagerFactory(entityManagerFactory);
    }

    /**
     * Ensure that the translator, generated by this factory, recognizes HSQL database
     * exceptions and thus is configured correctly.
     */
    @Test
    public void testTranslator() throws Exception {
        factory.setDefaultExceptionFactory(new DefaultViolationExceptionFactory());
        DatabaseConstraintExceptionTranslator translator = factory.getObject();
        RuntimeException hsqlException = new RuntimeException(UNIQUE_KEY_EXCEPTION_MESSAGE);
        Throwable resultException = translator.translateExceptionIfPossible(hsqlException);
        assertTrue(resultException instanceof UniqueKeyViolationException);
        assertEquals(translator, factory.getObject()); // Also ensure the translator is singleton
    }

    /**
     * Construct a translator that recognizes "uk_cars_license" constraint violations and
     * translates them into a custom license number already exists exception.
     */
    @Test
    public void testCustomExceptionIsRegistered() throws Exception {
        Map<String, Class<? extends Throwable>> exceptionClasses = new HashMap<String, Class<? extends Throwable>>();
        exceptionClasses.put("uk_cars_license", LicenseNumberAlreadyExistsException.class);
        factory.setExceptionClasses(exceptionClasses);
        DatabaseConstraintExceptionTranslator translator = factory.getObject();
        RuntimeException hsqlException = new RuntimeException(UNIQUE_KEY_EXCEPTION_MESSAGE);
        Throwable resultException = translator.translateExceptionIfPossible(hsqlException);
        assertTrue(resultException instanceof LicenseNumberAlreadyExistsException);
    }

    /**
     * Our license number already exists exception can also be thrown by a custom factory.
     */
    @Test
    public void testCustomFactoryIsRegistered() throws Exception {
        Map<String, DatabaseConstraintViolationExceptionFactory> exceptionFactories = new HashMap<String, DatabaseConstraintViolationExceptionFactory>();
        final DatabaseConstraintViolationExceptionFactory exceptionFactory = new LicenseNumberAlreadyExistsExceptionFactory();
        exceptionFactories.put("uk_cars_license", exceptionFactory);
        factory.setExceptionFactories(exceptionFactories);
        DatabaseConstraintExceptionTranslator translator = factory.getObject();
        RuntimeException hsqlException = new RuntimeException(UNIQUE_KEY_EXCEPTION_MESSAGE);
        Throwable resultException = translator.translateExceptionIfPossible(hsqlException);
        assertTrue(resultException instanceof LicenseNumberAlreadyExistsException);
        assertEquals(exceptionFactory, ((LicenseNumberAlreadyExistsException) resultException).getExceptionFactory());
    }

    @Test
    public void testGetObjectType() {
        assertEquals(DatabaseConstraintExceptionTranslator.class, factory.getObjectType());
    }

}
