package org.jarbframework.constraint.metadata.enhance;

import org.jarbframework.constraint.metadata.DatabaseGenerated;
import org.jarbframework.constraint.metadata.PropertyConstraintDescription;
import org.jarbframework.utils.bean.Annotations;

/**
 * Properties annotated with @DatabaseGenerated are never set to required
 * as they will be generated by the database on demand.
 * 
 * @author Jeroen van Schagen
 * @since 6 September 2011
 */
public class DatabaseGeneratedPropertyConstraintEnhancer implements PropertyConstraintEnhancer {

    @Override
    public void enhance(PropertyConstraintDescription description) {
        if (Annotations.hasAnnotation(description.toReference(), DatabaseGenerated.class)) {
            description.setRequired(false);
        }
    }

}
