package org.jarbframework.constraint.metadata.enhance;

import static org.jarbframework.utils.bean.AnnotationScanner.fieldOrGetter;

import org.jarbframework.constraint.metadata.PropertyConstraintDescription;
import org.jarbframework.constraint.metadata.database.DatabaseGenerated;

/**
 * Properties annotated with @DatabaseGenerated are never set to required
 * as they will be generated by the database on demand.
 * 
 * @author Jeroen van Schagen
 * @since 6 September 2011
 */
public class DatabaseGeneratedPropertyConstraintEnhancer implements PropertyConstraintEnhancer {

    @Override
    public PropertyConstraintDescription enhance(PropertyConstraintDescription propertyDescription) {
        if (fieldOrGetter().hasAnnotation(propertyDescription.toReference(), DatabaseGenerated.class)) {
            propertyDescription.setRequired(false);
        }
        return propertyDescription;
    }

}
